require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'scrollforruqqus' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'


  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'scrollforruqqusTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'scrollforruqqus-tvOS' do
  # Pods for scrollforruqqus-tvOS

  target 'scrollforruqqus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
