version: "2"
services:
  sfroa:
    container_name: scroll-for-ruqqus-auth-server
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    # ports:
    #   - 3001:3001
    volumes:
      - /var/domains/sfroa.danhab99.xyz:/var/listen.sock