version: "2"
services:
  sfroa:
    container_name: Scroll For Ruqqus Auth Server
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${NPA_SFROA_DANHAB99_XYZ_PORT}:3001
